openapi: 3.0.3
info:
  title: 生地の在庫管理システム
  version: 1.0.0
servers:
  - url: http://localhost:8080/v1
    description: Localhost server
  - url: http://api.excample.com/v1
    description: Production server
paths:
  /cloths:
    get:
      tags:
        - cloth
      summary: 生地一覧
      description: 所持している生地の一覧
      operationid: getCloths
      responses:
        "200":
          description: 生地の一覧
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Cloth"
    post:
      tags:
        - cloth
      summary: 生地追加
      description: 所持している生地の登録
      operationid: createCloths
      responses:
        "201":
          description: 生地の一覧
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cloth"
  /cloths/{clothId}:
    put:
      tags:
        - cloth
      summary: 生地変更
      description: 登録している生地の変更
      parameters:
        - $ref: "#/components/parameters/clothIdParam"
      responses:
        "204":
          description: 生地の更新
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cloth"
components:
  schemas:
    Cloth:
      type: object
      description: 生地データ
      required:
        - clothId
        - photo
        - price
        - createdAt
        - updatedAt
      properties:
        clothId:
          type: string
          description: 生地の ID
          example: cloth0001
        photo:
          type: string
          format: uri
          description: 生地の写真の URL
          example: https://example.com/cloth0001.jpg
        price:
          type: integer
          format: int32
          description: 10cm単位の価格
          example: 300
        createdAt:
          type: string
          format: date-time
          description: 作成日
        updatedAt:
          type: string
          format: date-time
          description: 更新日
          nullable: true
  parameters:
    clothIdParam:
      name: clothId
      in: path
      description: 生地の ID
      required: true
      schema:
        type: string
